---
abstract: 'Perl module for implementing a seed server (should not'
author:
  - 'Shlomi Fish, E<lt>shlomif@iglu.org.ilE<gt>'
build_requires: {}
configure_requires:
  Module::Build: 0.39
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SeedServe
provides:
  Net::SeedServe:
    file: lib/Net/SeedServe.pm
    version: v0.2.3
  Net::SeedServe::Server:
    file: lib/Net/SeedServe/Server.pm
requires:
  IO::All: 0.33
  Test::More: 0
  Time::HiRes: 1.59
  perl: 5.008
resources:
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://bitbucket.org/shlomif/gimp-test-suite
version: v0.2.3
